### PR TITLE
added more food options, removed evil tomato nonsense

### PR DESCRIPTION
**Pull request by marykatefain**

### CODE REVIEW

**Comment by alexgleason** [comment]
Missing commas on line 37 and 38

**Comment by alexgleason** [comment]
Missing comma on line 38

**Comment by alexgleason** [comment]
Are you really gonna have me merge 3 commits for this?

**Comment by marykatefain** [comment]
yes? O:)

Mary Kate Fain
Organizer, DxE Philly <http://dxephilly.org>
Founder, Philly Animal Rights Alliance
<http://phillyara.surge.sh/index.html>

Phone: 610-914-7610
Email: mkfain1@gmail.com
http://marykatefain.surge.sh/  <http://marykatefain.surge.sh/>

**Comment by alexgleason** [comment]
Nice work!

**Pull request merged**
