### PR TITLE
Programmed Twink to reply to requests for recipes

### PR DESCRIPTION
**Pull request by marykatefain**
In response to you and Chad...

### CODE REVIEW

**Comment by alexgleason** [comment]
I was thinking it could do this when it makes [dinner reminders](https://github.com/Uptwinkles/twink/blob/104d9a970a163e6ead6d3f33eb8677be12d8d26e/app/server.js#L48) rather than in response to a message.

I also don't know the best way to deal with responses to multiple things. I'm not sure using that whole piece of code twice makes more sense than using a conditional within [the piece that's already there](https://github.com/Uptwinkles/twink/blob/104d9a970a163e6ead6d3f33eb8677be12d8d26e/app/server.js#L16).

**Comment by marykatefain** [comment]
Can't you just include it for now and if you decide to do something more detailed later just do that then?

**Comment by alexgleason** [comment]
As you wish

**Comment by alexgleason** [comment]
lmgtfy uses nonfree JS

**Comment by alexgleason** [comment]
I refactored this https://github.com/Uptwinkles/twink/commit/ff7574f2177edaef9f7c31755f4f20a3d779225c

**Pull request merged**
